name: CI

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: package.json
        cache: 'npm'
    
    - name: Install Dependencies
      run: |
        npm ci
        # https://github.com/biomejs/biome/issues/4467#issuecomment-2514553517
        npm install @biomejs/cli-linux-x64
    
    - name: Check
      run: npm run check
